package SQL;

import java.util.Scanner;
import SQL.SQLConnector;


/**
 * Class representing the SQL Databse table User.
 * Contains a UserID, username, email, password and if it is an instructor or not
 * 
 * Also has its own SQLConnector @see SQLConnector
 */
public class CreateUser {
    int userID;
    String username;
    String email;
    String password;
    boolean instructor;
    SQLConnector connector = new SQLConnector();

    /**
     * Initialize a Course with the provided variables, UserID is given.
     * @param userID
     * @param username
     * @param email
     * @param password
     * @param instructor
     */
    public CreateUser(int userID, String username, String email, String password, boolean instructor) {
        this.userID = userID;
        this.username = username;
        this.email = email;
        this.password = password;
        this.instructor = instructor;

    }
    /**
     * Initialize a Course with the provided variables.
     * UserID is generated by the SQLConnector, this returns the next ID for the table user.
     * The user is inserted into the database
     * 
     * If the user is an instructor, the user is also inserted into the database table Instructor
     * If the user is an Student, the user is also inserted into the database table Student
     *  
     * @param userID
     * @param username
     * @param email
     * @param password
     * @param instructor
     */
    public CreateUser(String username, String email, String password, boolean instructor) {
        this.userID = this.connector.getNextID("UserID", "User");
        this.username = username;
        this.email = email;
        this.password = password;

        this.connector.insert(this.getValues());

        if (instructor) {
            int instructorID = this.connector.getNextID("InstructorID", "Instructor");
            this.connector.insert("INSERT INTO Instructor (UserID, InstructorID) VALUES ( " + "'" + this.userID + "', "
                    + "'" + instructorID + "')");
        } else {
            int StudentID = this.connector.getNextID("StudentID", "Student");
            this.connector.insert("INSERT INTO Student (UserID, StudentID) VALUES ( " + "'" + this.userID + "', " + "'"
                    + StudentID + "')");
        }
        
    }


    /**
     * Gets the username
     * @return String username
     */
    public String getName() {
        return this.username;
    }

    /**
     * Returns true if the user is an instructor
     * Retruns false if the user is a student
     * @return
     */
    public boolean getInstructor() {
        return this.instructor;
    }

    /**
     * Returns the userID
     * @return int, userID
     */
    public int getUserID() {
        return this.userID;
    }


    /** 
     * @return a String that is an insertStatement of the class variables.
    */
    public String getValues() {
        return "INSERT INTO USER (UserID, Username, Email, Password) " + "VALUES " + "(" + "'" + this.userID + "', "
                + "'" + this.username + "', " + "'" + this.email + "', " + "'" + this.password + "')";
    }

    /** 
     * @return printabel String
     */
    public String toString() {
        return "UserID: " + this.userID + " Username: " + this.username + " Email: " + this.email + " password: "
                + this.password;
    }

    public static void main(String[] args) {
    }
}
